### ISSUE TITLE
prop.O.from.water in r.calc but not ape.calc

### ISSUE THREAD

**Issue by jeffkimbrel** [jeffkimbrel/qSIP2#2]
In the original qSIP code the heavy max calculations for 18O doesn't include the `prop.O.from.water` adjustment, but it does in the `r.calc()` code. This leads to different values when calculating the AFE values than when calculating `r`. 

```r
# in r.calc()
MW.out$MW + (MW.out$Oatoms * prop.O.from.water * ((1.008665 * 2 * (1000000/(1000000+379.9+2005.20))) + (1.008665 * 1 * (379.9/(1000000+379.9+2005.20)))))


# in ape.calc()
MW.out$MW + (MW.out$Oatoms * ((1.008665 * 2 * (1000000/(1000000+379.9+2005.20))) + (1.008665 * 1 * (379.9/(1000000+379.9+2005.20)))))
```

**Comment by benkoch1** [comment]
The prop.O.from.water argument is only relevant to growth, not EAF because EAF values are absolute measures of isotopic enrichment that don’t care where the oxygen atoms in DNA come from.  If an organism uses less environmental water to build DNA than some other organism, it just ends up with lower enrichment.  But the growth estimate attempts to measure how much DNA is actually synthesized during the incubation period, and so that measurement needs to *try* and account for growth with both labeled oxygen and unlabeled oxygen.  The prop.O.water argument is the variable that is *trying* to do that.  (Asterisks used because it is likely a pretty rudimentary attempt!)  I haven’t yet looked through the new code on this in its full context, but as I recall, in the Bitbucket repo, the r.calc uses the equation you show to create the variable “heavy.MW” or something like that, whereas the ape.calc equation is calculating a slightly different variable, “heavy.max.MW”, which is an estimate of the maximum molecular weight attained if all oxygens were to be replaced with 18O.  The ‘heavy.MW’ variable from the r.calc equation tries to estimate the maximum molecular weight that is actually attainable, given the biology of that microbe: namely that some O’s in the DNA will likely never be replaced with 18O — no matter how high the growth rate — because the organism’s metabolism necessarily also uses some other, non-environmental-water O’s (with are unlabeled) to build new DNA.
